# -*- coding: utf-8 -*-
"""
/***************************************************************************
 OpenPlumes
                                 A QGIS plugin
 Open-source contaminant plume modeling and visualization tools for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by jose
        email                : jose.marmolejo688@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__author__ = 'jose'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by jose'


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load OpenPlumes class from file OpenPlumes.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .openplumes import OpenPlumesPlugin
    return OpenPlumesPlugin()
