# -*- coding: utf-8 -*-

"""
/***************************************************************************
 OpenPlumes
                                 A QGIS plugin
 Open-source contaminant plume modeling and visualization tools for QGIS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2026-07-10
        copyright            : (C) 2026 by jose
        email                : jose.marmolejo688@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

__author__ = 'jose'
__date__ = '2026-07-10'
__copyright__ = '(C) 2026 by jose'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink,QgsProcessingParameterField,
                       QgsProcessingParameterEnum)


class OpenPlumesAlgorithm(QgsProcessingAlgorithm):
    """
    This is an example algorithm that takes a vector layer and
    creates a new identical one.

    It is meant to be used as an example of how to create your own
    algorithms and explain methods and variables used to do it. An
    algorithm like this will be available in all elements, and there
    is not need for additional work.

    All Processing algorithms should extend the QgsProcessingAlgorithm
    class.
    """

    # Constants used to refer to parameters and outputs. They will be
    # used when calling the algorithm from another algorithm, or when
    # calling from the QGIS console.

    OUTPUT = 'OUTPUT'
    INPUT = 'INPUT'

    def initAlgorithm(self, config):
        """
        Here we define the inputs and output of the algorithm, along
        with some other properties.
        """

        # We add the input vector features source. It can have any kind of
        # geometry.
        self.addParameter(
            QgsProcessingParameterFeatureSource(
                self.INPUT,
                self.tr('Monitoring well layer'),
                [QgsProcessing.TypeVectorPoint]
            )
        )

        # Adding a section where it asks which contaminant
        # to model.
        self.addParameter(
            QgsProcessingParameterField(
                'CONTAMINANT_ATTRIBUTE',
                self.tr('Contaminant'),
                parentLayerParameterName=self.INPUT,
                type=QgsProcessingParameterField.Numeric
            )
        )


        self.addParameter(
            QgsProcessingParameterEnum(
                'SAMPLE_POSITION',
                self.tr('Representative sample position'),
                options=[
                    'Screen top',
                    'Screen midpoint',
                    'Screen bottom'
                ],
                defaultValue=1
            )
        )    
         
        # We add a feature sink in which to store our processed features (this
        # usually takes the form of a newly created vector layer when the
        # algorithm is run in QGIS).
        self.addParameter(
            QgsProcessingParameterFeatureSink(
                self.OUTPUT,
                self.tr('Output')
            )
        )

    def processAlgorithm(self, parameters, context, feedback):
        """
        Here is where the processing itself takes place.
        """

        # Retrieve the feature source and sink. The 'dest_id' variable is used
        # to uniquely identify the feature sink, and must be included in the
        # dictionary returned by the processAlgorithm function.
        source = self.parameterAsSource(parameters, self.INPUT, context)


        contaminant = self.parameterAsString(
            parameters,
            'CONTAMINANT_ATTRIBUTE',
            context
        )

        screen_top_attribute = self.parameterAsString(
            parameters,
            'SCREEN_TOP_ATTRIBUTE',
            context
        )

        screen_bottom_attribute = self.parameterAsString(
            parameters,
            'SCREEN_BOTTOM_ATTRIBUTE',
            context
        )

        sample_position = self.parameterAsEnum(
            parameters,
            'SAMPLE_POSITION',
            context
        )

        feedback.pushInfo(f'Contaminant: {contaminant}')
        feedback.pushInfo(f'Screen top attribute: {screen_top_attribute}')
        feedback.pushInfo(f'Screen bottom attribute: {screen_bottom_attribute}')
        feedback.pushInfo(f'Sample position index: {sample_position}')



        (sink, dest_id) = self.parameterAsSink(parameters, self.OUTPUT,
                context, source.fields(), source.wkbType(), source.sourceCrs())

        # Compute the number of steps to display within the progress bar and
        # get features from source
        total = 100.0 / source.featureCount() if source.featureCount() else 0
        features = source.getFeatures()

        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feedback.isCanceled():
                break
            screen_top = feature[screen_top_attribute]
            screen_bottom = feature[screen_bottom_attribute]
            concentration = feature[contaminant]            

            if sample_position == 0:
                sample_elevation = screen_top

            elif sample_position == 1:
                sample_elevation = (screen_top + screen_bottom) / 2

            elif sample_position == 2:
                sample_elevation = screen_bottom

            # Add a feature in the sink
            sink.addFeature(feature, QgsFeatureSink.FastInsert)

            # Update the progress bar
            feedback.setProgress(int(current * total))

        # Return the results of the algorithm. In this case our only result is
        # the feature sink which contains the processed features, but some
        # algorithms may return multiple feature sinks, calculated numeric
        # statistics, etc. These should all be included in the returned
        # dictionary, with keys matching the feature corresponding parameter
        # or output names.
        return {self.OUTPUT: dest_id}

    def name(self):
        """
        Returns the algorithm name, used for identifying the algorithm. This
        string should be fixed for the algorithm, and must not be localised.
        The name should be unique within each provider. Names should contain
        lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Create Plume'

    def displayName(self):
        """
        Returns the translated algorithm name, which should be used for any
        user-visible display of the algorithm name.
        """
        return self.tr(self.name())

    def group(self):
        """
        Returns the name of the group this algorithm belongs to. This string
        should be localised.
        """
        return self.tr(self.groupId())

    def groupId(self):
        """
        Returns the unique ID of the group this algorithm belongs to. This
        string should be fixed for the algorithm, and must not be localised.
        The group id should be unique within each provider. Group id should
        contain lowercase alphanumeric characters only and no spaces or other
        formatting characters.
        """
        return 'Plume modeling'

    def tr(self, string):
        return QCoreApplication.translate('Processing', string)

    def createInstance(self):
        return OpenPlumesAlgorithm()
